name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Run daily
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Infinite-L00pBaCk
          outputs: |
            github-snake-dark.svg?palette=github-dark&color_snake=#00FFFF

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add github-snake-dark.svg
          git commit -m "chore: updated snake animation" || exit 0
          git push origin main
